server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/leesunghee/dev/spring_cloud/config-service/spring_cloud_config
          uri: https://github.com/Leesunghee/config-service
#          username: realwunz@gmail.com
#          password: ready2di@####